//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDataBuilderGenerator {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestDataBuilderGenerator.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In der Factory wird eine Methode erwartet, die einen Builder für diesen Typ erzeugt. ähnelt.
        /// </summary>
        public static string FactoryMethodForBuilderExpected_Diagnostic_Description {
            get {
                return ResourceManager.GetString("FactoryMethodForBuilderExpected_Diagnostic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In der Factory wird eine Methode zum Erzeugen des Builders für den Typ [{0}] erwartet. ähnelt.
        /// </summary>
        public static string FactoryMethodForBuilderExpected_Diagnostic_Message {
            get {
                return ResourceManager.GetString("FactoryMethodForBuilderExpected_Diagnostic_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Factory Methode ähnelt.
        /// </summary>
        public static string FactoryMethodForBuilderExpected_Diagnostic_Title {
            get {
                return ResourceManager.GetString("FactoryMethodForBuilderExpected_Diagnostic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Builder muss es eine Methode zum Setzen des Feldes geben. ähnelt.
        /// </summary>
        public static string FieldShouldHaveSetterMethodInBuilder_Diagnostic_Description {
            get {
                return ResourceManager.GetString("FieldShouldHaveSetterMethodInBuilder_Diagnostic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Builder enthält keine Setter-Methode für das Feld [{0}]. ähnelt.
        /// </summary>
        public static string FieldShouldHaveSetterMethodInBuilder_Diagnostic_Message {
            get {
                return ResourceManager.GetString("FieldShouldHaveSetterMethodInBuilder_Diagnostic_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Setter Methode in Builder ähnelt.
        /// </summary>
        public static string FieldShouldHaveSetterMethodInBuilder_Diagnostic_Title {
            get {
                return ResourceManager.GetString("FieldShouldHaveSetterMethodInBuilder_Diagnostic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für den Typ wird ein Builder erwartet, der das Erstellen von Instanzen dieses Typs vereinfacht. ähnelt.
        /// </summary>
        public static string TypeShouldHaveBuilder_Diagnostic_Description {
            get {
                return ResourceManager.GetString("TypeShouldHaveBuilder_Diagnostic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für den Typ [{0}] existiert kein Builder. ähnelt.
        /// </summary>
        public static string TypeShouldHaveBuilder_Diagnostic_Message {
            get {
                return ResourceManager.GetString("TypeShouldHaveBuilder_Diagnostic_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typ hat keinen Builder ähnelt.
        /// </summary>
        public static string TypeShouldHaveBuilder_Diagnostic_Title {
            get {
                return ResourceManager.GetString("TypeShouldHaveBuilder_Diagnostic_Title", resourceCulture);
            }
        }
    }
}
